user:
  test001:
    username: william
    password: 1234abcd!
  test002:
    username: 周杰伦
    password: 1234abcd!

url: http://www.tcpjwtester.top

mysql:
  db: autotest
  host: localhost
  password: 123456
  port: 3306
  user: root